repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  # js
  - repo: local
    hooks:
      - id: husky-run-pre-commit
        name: husky
        language: system
        entry: ./others/.husky/pre-commit
        pass_filenames: false
        always_run: true

  # python
  - repo: https://github.com/python-poetry/poetry
    # export poetry to requirements.txt(without python version after)
    rev: "1.6.1"
    hooks:
      - id: poetry-check
        args: ["-C", "./subdirectory"]
      - id: poetry-lock
        args: ["-C", "./subdirectory"]
      - id: poetry-export
        args:
          [
            "-C",
            "./server",
            "--without-hashes",
            "--without-urls",
            "|",
            "awk",
            "'{ print $1 }'",
            "FS=';'",
            ">",
            "./server/requirements.txt",
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      # mypy for server
      - id: mypy
        name: mypy-server
        files: ^server/
      # mypy for admin_server
      - id: mypy
        name: mypy-admin-server
        files: ^admin_server/

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      # formatter
      - id: black
        args: [--safe]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      # linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # formatter unsave(beta)
      - id: ruff-format
        args: [--check]
