name: Server test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  server-code-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image docker
        run: docker-compose build server

      - name: Install dependencies
        # create sample .env file
        # install dependencies
        run: |
          bash others/create_sample_env.sh
          docker-compose run --rm server poetry install --only-root

      # TODO: cannot run docker-compose test
      - name: Run tests
        run: docker-compose run --rm server python --version
