name: Server test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  server-code-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            server
            mongo
          test-container: server
          test-command: "poetry install --only-root"
